<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercise 2 : Using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #742082;
      }

      .quarto-title-block .quarto-title-banner {
        color: #742082;
background: white;
      }
</style>


<link rel="stylesheet" href="ukds.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Merging Data and Applying Weights_Using R.html">Merging Data and Applying Weights</a></li><li class="breadcrumb-item"><a href="./Merging Data and Applying Weights_Using R.html">Exercise 2 : Using R</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Merging Data and Applying Weights_Using R.html">Merging Data and Applying Weights</a></li><li class="breadcrumb-item"><a href="./Merging Data and Applying Weights_Using R.html">Exercise 2 : Using R</a></li></ol></nav>
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exercise 2 : Using R</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./pics/UKDS_Logos_Col_Grey_300dpi.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">The Hierarchical and Flat File Datasets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Hierarchical and Flat File_Using R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 1 : Using R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Hierarchical and Flat File_Using SPSS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 1 : Using SPSS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Merging Data and Applying Weights</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Merging Data and Applying Weights_Using R.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Exercise 2 : Using R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Merging Data and Applying Weights_Using SPSS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 2 : Using SPSS</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a>
  <ul class="collapse">
  <li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset">1. The dataset</a></li>
  <li><a href="#setting-up-r" id="toc-setting-up-r" class="nav-link" data-scroll-target="#setting-up-r">2. Setting up R</a>
  <ul class="collapse">
  <li><a href="#loading-the-r-packages" id="toc-loading-the-r-packages" class="nav-link" data-scroll-target="#loading-the-r-packages">Loading the R packages</a></li>
  <li><a href="#setting-up-the-working-directory" id="toc-setting-up-the-working-directory" class="nav-link" data-scroll-target="#setting-up-the-working-directory">Setting up the working directory</a></li>
  <li><a href="#importing-reading-data-into-r" id="toc-importing-reading-data-into-r" class="nav-link" data-scroll-target="#importing-reading-data-into-r">Importing (reading) data into R</a></li>
  <li><a href="#opening-the-two-frs-tables-in-spss-format-in-r" id="toc-opening-the-two-frs-tables-in-spss-format-in-r" class="nav-link" data-scroll-target="#opening-the-two-frs-tables-in-spss-format-in-r">Opening the two FRS tables in SPSS format in R</a></li>
  </ul></li>
  <li><a href="#preparing-the-datasets" id="toc-preparing-the-datasets" class="nav-link" data-scroll-target="#preparing-the-datasets">3. Preparing the datasets</a></li>
  <li><a href="#the-variables" id="toc-the-variables" class="nav-link" data-scroll-target="#the-variables">4. The variables</a></li>
  </ul></li>
  <li><a href="#explore-the-datasets" id="toc-explore-the-datasets" class="nav-link" data-scroll-target="#explore-the-datasets">Explore the datasets</a>
  <ul class="collapse">
  <li><a href="#examining-the-variables" id="toc-examining-the-variables" class="nav-link" data-scroll-target="#examining-the-variables">Examining the variables</a></li>
  </ul></li>
  <li><a href="#merging-datasets" id="toc-merging-datasets" class="nav-link" data-scroll-target="#merging-datasets">Merging datasets</a>
  <ul class="collapse">
  <li><a href="#merging-data-in-r" id="toc-merging-data-in-r" class="nav-link" data-scroll-target="#merging-data-in-r">Merging data in R</a></li>
  </ul></li>
  <li><a href="#applying-the-weight" id="toc-applying-the-weight" class="nav-link" data-scroll-target="#applying-the-weight">Applying the weight</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Since the FRS data are collected at different levels—households, families (benefit units), and individuals (persons)—and provided in multiple files, you may at some point want to conduct analysis across different levels. Some files focus on specialised topics such as assets, childcare, mortgages, and pensions, which may require exploring associations between variables entered in separate files.</p>
<p>For example, what if we want to examine how pension type varies across genders?</p>
<p>In that case, it is necessary to combine data, as the two variables of interest are entered in different FRS datasets.</p>
<p>In this exercise, we will show how to merge data from the 2022–2023 Family Resources Survey (FRS) to explore the association between variables available in various FRS datasets. We will also assess the effect of survey weights on the results using R.</p>
<section id="getting-started" class="level1">
<h1>Getting started</h1>
<section id="the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="the-dataset">1. The dataset</h2>
<p>The dataset we will be using in this exercise is the <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9252">Family Resources Survey, 2022-2023</a>. These data are <a href="https://www.ukdataservice.ac.uk/get-data/data-access-policy">safeguarded</a>. You can download them from the UK Data Service after <a href="https://ukdataservice.ac.uk/help/registration/registration-login-faqs/">registration</a>.</p>
<p>To get the Family Resources Survey (FRS), 2022-2023 dataset, go to the data <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9252">catalogue page</a>, login to your account (create an account if you do not already have one), download and save the SPSS version, which we will use in this exercise.</p>
<p>Create a new folder to save the downloaded data and analysis work in appropriate location on your machine and give that folder a name.</p>
<p>The exercise below assumes that the dataset has been saved in a new folder named UKDS on your Desktop (Windows computers). The path would typically be <code>C:\\Users\\YOUR_USER_NAME\\Desktop\\UKDS</code>. You can change it to the location that best suits you.</p>
<p>Remember to adjust the code below to match the location of the data on your machine.</p>
<p>The FRS is a hierarchical dataset provided every year in multiple data files (known as ‘tables’ in the FRS language). The number of these tables varies, depending on the year of the survey. The 2022-2023 FRS has 25 tables. In this exercise, we will use the general-purpose table “adult.sav” and the specialised table “pension.sav” to:</p>
<ul>
<li>Merge datasets to explore the association between variables available in different FRS tables.</li>
<li>Apply the survey weights and compare unweighted and weighted frequencies and percentages.</li>
</ul>
</section>
<section id="setting-up-r" class="level2">
<h2 class="anchored" data-anchor-id="setting-up-r">2. Setting up R</h2>
<p>We start with loading all R packages we will be using for this exercise, set the working directory, and import (read) the data into R.</p>
<section id="loading-the-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-r-packages">Loading the R packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)      <span class="co"># Data manipulation functions</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)      <span class="co"># Extra statistical functions</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># Data manipulation and visualization</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)    <span class="co"># Data cleaning and summary table</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)      <span class="co"># Tables in Quarto</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="setting-up-the-working-directory" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-the-working-directory">Setting up the working directory</h3>
<p><strong>Note</strong>: Adjust the <code>setwd()</code> command below to match the location of the data on your computer</p>
<p>setwd(“C:_Username_here”) # Setting up the working directory</p>
<p>getwd() # getting the working directory</p>
</section>
<section id="importing-reading-data-into-r" class="level3">
<h3 class="anchored" data-anchor-id="importing-reading-data-into-r">Importing (reading) data into R</h3>
<p>There are several packages for importing data with different formats into R. The most used packages are <code>haven</code>, <code>foreign</code>, and <code>readr</code>.</p>
<p>In this exercise, we use the <code>haven</code> package to import the four FRS tables that we will work with as SPSS files.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)                    <span class="co"># load the package haven </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Note</strong>: If the package <code>haven</code> is already installed in the R environment, you just need to recall it from the R library using the function <code>library(haven)</code>. If not, you can install it using: <code>install.packages("haven")</code>.</p>
<p>For instructions and information about some R packages for importing data with different format into R, see our <a href="https://trainingmodules.ukdataservice.ac.uk/crime/#/lessons/eNqUS0tUWq1sC5DMKiLpxGaTuE5f-sj6">Data Skills Module: Exploring crime surveys with R</a>.</p>
</section>
<section id="opening-the-two-frs-tables-in-spss-format-in-r" class="level3">
<h3 class="anchored" data-anchor-id="opening-the-two-frs-tables-in-spss-format-in-r">Opening the two FRS tables in SPSS format in R</h3>
<p>Next, we assign a name to the data we want to import into R. We will name the two FRS tables that we want to import to R as frs_adult2223 and frs_pension2223.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign names to the data we want to import into R</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>frs_adult2223 <span class="ot">&lt;-</span> <span class="fu">read_sav</span> (<span class="st">"UKDA-9252-spss/spss/spss28/adult.sav"</span>) </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>frs_pension2223 <span class="ot">&lt;-</span> <span class="fu">read_sav</span> (<span class="st">"UKDA-9252-spss/spss/spss28/pension.sav"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="preparing-the-datasets" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-datasets">3. Preparing the datasets</h2>
<p>After loading the FRS tables into R, we begin with exploring the frs_adult2223 and frs_pension2223 datasets.</p>
<p>But first, we will have a quick look at the number of observations and the number of the variables in these tables using the <code>dim()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(frs_adult2223)          <span class="co">#Gives the number of rows (observations) and columns (variables) in the frs_adult2223 file</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42480   587</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(frs_pension2223)        <span class="co">#Gives the number of rows (observations) and columns (variables) in the frs_pension2223 file</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15233    50</code></pre>
</div>
</div>
<p>You can see that frs_adult2223 table has 587 variables. The specialised table frs_pension2223 has less variables (50 variables).</p>
</section>
<section id="the-variables" class="level2">
<h2 class="anchored" data-anchor-id="the-variables">4. The variables</h2>
<p>In this exercise, we will use only a few variables from each table. Therefore, we will create subset datasets from these two tables, containing the variables needed for the exercise. The tables below display the selected variables (names and labels) from each table.</p>
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable name</strong></th>
<th><strong>Variable label</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Variables from the frs_adult2223 table</strong></td>
<td></td>
</tr>
<tr class="even">
<td>SERNUM</td>
<td>Sernum</td>
</tr>
<tr class="odd">
<td>BENUNIT</td>
<td>Benefit Unit</td>
</tr>
<tr class="even">
<td>PERSON</td>
<td>Person</td>
</tr>
<tr class="odd">
<td>HEALTH1</td>
<td>Whether has a long standing illness</td>
</tr>
<tr class="even">
<td>SEX</td>
<td>Sex</td>
</tr>
<tr class="odd">
<td>IAGEGR4</td>
<td>Individual Adult 5 Year Age Bands - Anon</td>
</tr>
<tr class="even">
<td>GROSS4</td>
<td>Grossing variable</td>
</tr>
<tr class="odd">
<td><strong>Variables from the frs_pension2223 table</strong></td>
<td></td>
</tr>
<tr class="even">
<td>SERNUM</td>
<td>Sernum</td>
</tr>
<tr class="odd">
<td>BENUNIT</td>
<td>Benefit Unit</td>
</tr>
<tr class="even">
<td>PERSON</td>
<td>Person</td>
</tr>
<tr class="odd">
<td>PENPAY</td>
<td>Amount of last payment from pension (continuous variable)</td>
</tr>
<tr class="even">
<td>PENTYPE</td>
<td>Pension Type</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create subset datasets from the original data files  </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#use a pipeline (the %&gt;% operator)  </span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#and the "select" function from the dplyr package </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#the code below only selects the variables we are interested in</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#We will name the new datasets as frs_adult2223_short and frs_pension2223. </span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>frs_adult2223_short <span class="ot">&lt;-</span> frs_adult2223 <span class="sc">%&gt;%</span> <span class="fu">select</span> (SERNUM, BENUNIT, PERSON, GROSS4, HEALTH1, SEX, IAGEGR4) </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>frs_pension2223_short <span class="ot">&lt;-</span> frs_pension2223<span class="sc">%&gt;%</span> <span class="fu">select</span> (SERNUM, BENUNIT, PERSON, PENPAY, PENTYPE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="explore-the-datasets" class="level1">
<h1>Explore the datasets</h1>
<p>If you want to learn more about the two newly generated datasets frs_adult2223_short and frs_pension2223_short, see “<a href="https://ukdataserviceopen.github.io/Introduction_to_the_FRS1/Hierarchical%20and%20Flat%20File_Using%20R.html#explore-the-datasets">Explore the datasets</a>” section in <a href="https://ukdataserviceopen.github.io/Introduction_to_the_FRS1/Hierarchical%20and%20Flat%20File_Using%20R.html">Exercise 1 : Using R</a>.</p>
<section id="examining-the-variables" class="level2">
<h2 class="anchored" data-anchor-id="examining-the-variables">Examining the variables</h2>
<p>Let’s now examine the frequency of the variables HEALTH1, SEX, and IAGEGR4 in the frs_adult2223_short dataset.</p>
<p>We can use the <code>table()</code> function to create a frequency table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span> (frs_adult2223_short<span class="sc">$</span>HEALTH1)     <span class="co">#Create a frequency table for the variable HEALTH1 </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18308 24172 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_adult2223_short<span class="sc">$</span>SEX)          <span class="co">#Create a frequency table for the variable SEX</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
20143 22337 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_adult2223_short<span class="sc">$</span>IAGEGR4)      <span class="co">#Create a frequency table for the variable IAGEGR4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   4    5    6    7    8    9   10   11   12   13   14   15   16 
 587 1864 2506 3108 3341 3367 3002 3401 3763 3894 3751 3830 6066 </code></pre>
</div>
</div>
<p>We can use the <code>as_factor()</code> function (included in the <code>haven</code> package) to convert the categorical variables HEALTH1, SEX, and IAGEGR4 into factor variables. The newly generated factor variables HEALTH1f, SEXf, and IAGEGR4f are equivalent to categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>frs_adult2223_short<span class="sc">$</span>HEALTH1f<span class="ot">&lt;-</span><span class="fu">as_factor</span>(frs_adult2223_short<span class="sc">$</span>HEALTH1)      <span class="co">#Create a new factor variable HEALTH1f from the original variable HEALTH1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>frs_adult2223_short<span class="sc">$</span>SEXf<span class="ot">&lt;-</span><span class="fu">as_factor</span>(frs_adult2223_short<span class="sc">$</span>SEX)            <span class="co"># Create a new factor variable SEXf from the original variable SEX     </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>frs_adult2223_short<span class="sc">$</span>IAGEGR4f<span class="ot">&lt;-</span><span class="fu">as_factor</span>(frs_adult2223_short<span class="sc">$</span>IAGEGR4)    <span class="co"># Create a new factor variable IAGEGR4f from the original variable IAGEGR4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_adult2223_short<span class="sc">$</span>HEALTH1f)       <span class="co"># Create a frequency table for the new factor variable HEALTH1f</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Yes    No 
18308 24172 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_adult2223_short<span class="sc">$</span>SEXf)           <span class="co"># Create a frequency table for the new factor variable SEXf</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Male Female 
 20143  22337 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_adult2223_short<span class="sc">$</span>IAGEGR4f)       <span class="co"># Create a frequency table for the new factor variable IAGEGR4f</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Age 16 to 19   Age 20 to 24   Age 25 to 29   Age 30 to 34   Age 35 to 39 
           587           1864           2506           3108           3341 
  Age 40 to 44   Age 45 to 49   Age 50 to 54   Age 55 to 59   Age 60 to 64 
          3367           3002           3401           3763           3894 
  Age 65 to 69   Age 70 to 74 Age 75 or over 
          3751           3830           6066 </code></pre>
</div>
</div>
<p>Let’s now examine the frequency of the variable PENTYPE in the frs_ frs_pension2223_short dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span> (frs_pension2223_short<span class="sc">$</span>PENTYPE)       <span class="co"># Create a frequency table for the variable PENTYPE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6 
11156  2845   880   211    53    88 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>frs_pension2223_short<span class="sc">$</span>PENTYPEf<span class="ot">&lt;-</span><span class="fu">as_factor</span>(frs_pension2223_short<span class="sc">$</span>PENTYPE)    <span class="co"># Create a new factor variable PENTYPEf from the original variable 'PENTYPE’</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_pension2223_short<span class="sc">$</span>PENTYPEf)       <span class="co"># Create a frequency table for the new factor variable PENTYPEf</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Employee pension - occupational, workplace, group personal 
                                                       11156 
                                 Individual personal pension 
                                                        2845 
Survivor‹s pension (workplace or individual personal pension 
                                                         880 
   Income from an annuity ’ not purchased with pension funds 
                                                         211 
                             Income from a trust or covenant 
                                                          53 
Share of employee or personal pension from ex-spouse/partner 
                                                          88 </code></pre>
</div>
</div>
<p>The amount of last payment from pension PENPAY is a continuous variable. So, we will use <code>summary()</code> instead of <code>table()</code>. The <code>summary()</code> function provides a summary of the main statistics including the minimum and maximum values, the mean, the median and the quartiles. This function is useful for assessing and detecting extreme values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">summary</span>(frs_pension2223_short<span class="sc">$</span>PENPAY)      <span class="co">#Create a summary table for the variable PENPAY</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.      NA's 
   0.0002   32.2192   88.1425  155.2260  211.2370 1562.5645       490 </code></pre>
</div>
</div>
</section>
</section>
<section id="merging-datasets" class="level1">
<h1>Merging datasets</h1>
<p>To merge data, you need to use a common identifier - unique keys present across all datasets involved in the merge.</p>
<p>The Background Information and Methodology document within the <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9252#!/documentation">FRS 2022-23 documentation</a> provides us with the necessary information: what are the available identifiers and how to use them depending on which datasets we want to merge.</p>
<p>In our case, we will use the SERNUM, BENUNIT and PERSON variables to merge the two datasets: frs_adult2223_short and frs_pension2223_short. Sernum represents the unique serial number of the household, Benunit represents the identifier for the benefit unit (family) in the household, and PERSON represents the identifier for the individual. These variables are available in the two datasets we want to merge.</p>
<section id="merging-data-in-r" class="level2">
<h2 class="anchored" data-anchor-id="merging-data-in-r">Merging data in R</h2>
<p>There are several types of data merge in R (inner join, left join, right join, full outer join and cross join). So, when merging two datasets using three key variables, the number of observations in the merged dataset depends on the type of merge and how the key variables will match across the two datasets. For successful merge, the key variables must match exactly between the two datasets. Otherwise, observations will not match. Also, since the merge is carried out based on combinations of the three key variables, if two observations match based on one or two of the keys, they will not be merged.</p>
<p>In this example, we will use inner merge. So, we expect that the number of observations in the merged dataset will be equal to the number of observations in the smaller dataset that have all three key variables in the larger dataset. The exact number of observations in the merged dataset depends on how many of the three key variables match between the two datasets.</p>
<p>The two variables we are focusing on: SEXf, which measures gender is in frs_adult2223_short, and PENTYPE, which measures Pension Type is in frs_pension2223_short.</p>
<p>To merge frs_adult2223_short and frs_pension2223_short datasets, we use the following code (we will name the new data merged_data):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>merged_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(frs_adult2223_short,frs_pension2223_short, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"SERNUM"</span>, <span class="st">"BENUNIT"</span>, <span class="st">"PERSON"</span>))   <span class="co"># Specify which datasets to merge and which columns to use for merging</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Note</strong>: By default, if you do not specify the parameter ‘all’, the <code>merge</code> function carry out an inner join, which keeps only the rows that have matching values in all three key columns in both datasets.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Questions</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ol type="1">
<li>How many observations in the new merged_data dataset?</li>
<li>How many variables in the new merged_data dataset?</li>
<li>Did you expect that outcome?</li>
</ol>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<ol type="1">
<li>There are 15233 observations in the new merged_data as in frs_pension2223_short dataset.</li>
<li>There are 13 variables in the new merged_data including the four created factors, which is the total number of variables in both frs_adult2223_short and frs_pension2223_short datasets.</li>
<li>This outcome is expected because the new merged data will include all the matched observations (rows) based on the total number of unique key combinations in both datasets. In this case, the three unique keys we used from both datasets SERNUM, BENUNIT and PERSON matched 15233 observations between the two datasets frs_adult2223_short and frs_pension2223_short, which are all the observations in frs_pension2223_short dataset (the smaller dataset). Also, the number of variables in the new merged_data (13 variables) represents the total number of variables in frs_adult2223_short and frs_pension2223_short datasets.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(merged_data)              <span class="co"># Get the number of observations and variables in the new merged_data dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15233    13</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(merged_data)            <span class="co">#Get the names of variables in the new merged_data dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "SERNUM"   "BENUNIT"  "PERSON"   "GROSS4"   "HEALTH1"  "SEX"     
 [7] "IAGEGR4"  "HEALTH1f" "SEXf"     "IAGEGR4f" "PENPAY"   "PENTYPE" 
[13] "PENTYPEf"</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Before we assess the association between PENTYPEf and SEXf, let’s check the frequencies of the two variables after merging the two datasets frs_adult2223_short and frs_pension2223_short.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(merged_data<span class="sc">$</span>SEXf)       <span class="co"># Frequency tables of gender SEXf after merging frs_adult2223_short and frs_pension2223_short </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Male Female 
  8244   6989 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(merged_data<span class="sc">$</span>PENTYPEf)    <span class="co"># Frequency tables of pension type PENTYPEf after the merge</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Employee pension - occupational, workplace, group personal 
                                                       11156 
                                 Individual personal pension 
                                                        2845 
Survivor‹s pension (workplace or individual personal pension 
                                                         880 
   Income from an annuity ’ not purchased with pension funds 
                                                         211 
                             Income from a trust or covenant 
                                                          53 
Share of employee or personal pension from ex-spouse/partner 
                                                          88 </code></pre>
</div>
</div>
<p>To assess the association between pension type PENTYPEf and gender SEXf (how pension type varies by gender), we use the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(merged_data<span class="sc">$</span>PENTYPEf,merged_data<span class="sc">$</span>SEXf)     <span class="co"># How pension type varies by gender</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                              
                                                               Male Female
  Employee pension - occupational, workplace, group personal   6107   5049
  Individual personal pension                                  1893    952
  Survivor‹s pension (workplace or individual personal pension   98    782
  Income from an annuity ’ not purchased with pension funds     113     98
  Income from a trust or covenant                                27     26
  Share of employee or personal pension from ex-spouse/partner    6     82</code></pre>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Questions</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ul>
<li>Which type of pension was the least common for men and women?</li>
</ul>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<ul>
<li>‘Share of employee or personal pension from ex-spouse/partner’ was the least common pension type for men. ‘Income from a trust or covenant’ was the least common pension type for women.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="applying-the-weight" class="level1">
<h1>Applying the weight</h1>
<p>Now, we will apply the <code>svytable()</code> function to create <strong>weighted frequencies and percentages</strong> for the variable PENTYPEf. We will then compare the results with the <strong>unweighted</strong> analyses.</p>
<p><strong>PENTYPEf (weighted frequency table)</strong></p>
<ol type="1">
<li>First, we install the survey package and load it into the R session.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">library</span>(survey)          <span class="co"># Load it into R session</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Then, we declare the weight GROSS4 using svydesign()</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>merged_data_design<span class="ot">&lt;-</span><span class="fu">svydesign</span>(<span class="at">data =</span> merged_data, <span class="at">id =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">nest =</span> <span class="cn">TRUE</span>,<span class="at">weights =</span> merged_data<span class="sc">$</span>GROSS4)    <span class="co"># Using the svydesign() function to declare the weight</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>To create the <strong>weighted frequency table</strong> for the PENTYPEf variable, use:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>PENTYPEf,merged_data_design)    <span class="co"># Creating weighted frequency table using svytable()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PENTYPEf
  Employee pension - occupational, workplace, group personal 
                                                    10251385 
                                 Individual personal pension 
                                                     2560245 
Survivor‹s pension (workplace or individual personal pension 
                                                      829424 
   Income from an annuity ’ not purchased with pension funds 
                                                      185215 
                             Income from a trust or covenant 
                                                       59310 
Share of employee or personal pension from ex-spouse/partner 
                                                       86587 </code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We can also run <strong>weighted percentages</strong> for the PENTYPEf variable using <code>prop.table(svytable())</code> and round the results using <code>round()</code> function:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">svytable</span>(<span class="sc">~</span>PENTYPEf,merged_data_design)),<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>     <span class="co"># Creating weighted percentages using prop.table(svytable()) and round the results to four digits using round() function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PENTYPEf
  Employee pension - occupational, workplace, group personal 
                                                       73.37 
                                 Individual personal pension 
                                                       18.32 
Survivor‹s pension (workplace or individual personal pension 
                                                        5.94 
   Income from an annuity ’ not purchased with pension funds 
                                                        1.33 
                             Income from a trust or covenant 
                                                        0.42 
Share of employee or personal pension from ex-spouse/partner 
                                                        0.62 </code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Now we run <strong>unweighted frequencies and percentages</strong> for the PENTYPEf variable to compare with the weighted frequencies and percentages:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(merged_data<span class="sc">$</span>PENTYPEf)          <span class="co"># Creating unweighted frequency table </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Employee pension - occupational, workplace, group personal 
                                                       11156 
                                 Individual personal pension 
                                                        2845 
Survivor‹s pension (workplace or individual personal pension 
                                                         880 
   Income from an annuity ’ not purchased with pension funds 
                                                         211 
                             Income from a trust or covenant 
                                                          53 
Share of employee or personal pension from ex-spouse/partner 
                                                          88 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(merged_data<span class="sc">$</span>PENTYPEf, <span class="at">useNA =</span> <span class="st">"ifany"</span>)) ,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>    <span class="co">#Creating unweighted percentages using prop.table() and round the results to four digits using round() functions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Employee pension - occupational, workplace, group personal 
                                                       73.24 
                                 Individual personal pension 
                                                       18.68 
Survivor‹s pension (workplace or individual personal pension 
                                                        5.78 
   Income from an annuity ’ not purchased with pension funds 
                                                        1.39 
                             Income from a trust or covenant 
                                                        0.35 
Share of employee or personal pension from ex-spouse/partner 
                                                        0.58 </code></pre>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Questions</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<ol type="1">
<li>Do the frequencies change when the weight is applied?</li>
<li>Are there differences between the percentages of PENTYPEf for the weighted and unweighted analyses?</li>
</ol>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<ol type="1">
<li>Yes, the frequencies change substantially; the frequencies are much higher when the weight is applied. The large change is because the weights in the FRS sum to known population totals, which helps population totals to be estimated easily.</li>
</ol>
<p>The weights in the FRS also ensure that estimates reflect the sample design so that cases with a lower probability of selection will receive a higher weight to compensate for differential non-response among different subgroups in the population, and as such should help guard against potential non-response bias.</p>
<ol start="2" type="1">
<li>We summarise the weighed and unweighted percentages of PENTYPEf in the table below to make the comparison easier:</li>
</ol>
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 52%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th><strong>PENTYPEf</strong></th>
<th><strong>Weighted (%)</strong></th>
<th><strong>Unweighted (%)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Employee pension - occupational, workplace, group personal</td>
<td>73.37</td>
<td>73.24</td>
</tr>
<tr class="even">
<td>Individual personal pension</td>
<td>18.32</td>
<td>18.68</td>
</tr>
<tr class="odd">
<td>Survivor‹s pension (workplace or individual personal pension</td>
<td>5.94</td>
<td>5.78</td>
</tr>
<tr class="even">
<td>Income from an annuity ’ not purchased with pension funds</td>
<td>1.33</td>
<td>1.39</td>
</tr>
<tr class="odd">
<td>Income from a trust or covenant</td>
<td>0.42</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>Share of employee or personal pension from ex-spouse/partner</td>
<td>0.62</td>
<td>0.58</td>
</tr>
</tbody>
</table>
<p>You can see that there are very small differences between the percentages of PENTYPEf for the weighted and unweighted analyses. However, that is not always the case. You should always apply weights when you conduct data analysis.</p>
</div>
</div>
</div>
<p><strong>Your turn!</strong></p>
<p>Carry out a weighted and unweighted analysis to assess the frequencies and percentages of the gender variable in the merged_data (use the variable: SEXf).</p>
<p><strong>Outcome!</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>SEXf,merged_data_design)    <span class="co"># Creating weighted frequencies for SEXf using svytable()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SEXf
   Male  Female 
7428120 6544046 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">svytable</span>(<span class="sc">~</span>SEXf,merged_data_design)),<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>       <span class="co"># Creating weighted percentages for SEXf using prop.table(svytable()) and round the results to four digits using round() function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SEXf
  Male Female 
 53.16  46.84 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(merged_data<span class="sc">$</span>SEXf)          <span class="co"># Creating unweighted frequency table for SEXf</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Male Female 
  8244   6989 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(merged_data<span class="sc">$</span>SEXf, <span class="at">useNA =</span> <span class="st">"ifany"</span>)) ,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>    <span class="co"># Creating unweighted percentages using prop.table() and round the results to four digits using round() functions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Male Female 
 54.12  45.88 </code></pre>
</div>
</div>
<p>We summarise the weighed and unweighted percentages of SEXf in the table below to make the comparison easier:</p>
<table class="table-striped table-hover table">
<thead>
<tr class="header">
<th><strong>SEXf</strong></th>
<th><strong>Weighted (%)</strong></th>
<th><strong>Unweighted (%)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Male</td>
<td>53.16</td>
<td>54.12</td>
</tr>
<tr class="even">
<td>Female</td>
<td>46.84</td>
<td>45.88</td>
</tr>
</tbody>
</table>
<p>There are noticeable changes in the frequencies of SEXf when the weight is applied (they are much higher). But the differences between the percentages for the weighted and unweighted analysis are small.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>